### ISSUE TITLE
: No such file or directory

### ISSUE THREAD

**Issue by jesuslinares** [http-auth/htpasswd#6]
Hi,

Why I can't call the binary outside of node_modules?

```
root@localhost:/home/API# ./node_modules/htpasswd/bin/htpasswd -c myfile myuser
: No such file or directory

root@localhost:/home/API/node_modules/htpasswd/bin# htpasswd -c myfile myuser
New password:
Re-type new password:
Adding password for user myuser
```

It is happening the same if I install it globally (-g).
I'm using CentOS 7.

Regards.

**Comment by gevorg** [comment]
Just use `htpasswd -c myfile myuser` from both locations without `./node_modules/htpasswd/bin/` prefix.

Let me know if it works.

**Comment by jesuslinares** [comment]
It only works if I change the file htpasswd from Windows format (CRLF) to Linux format (LF).
Also, I think the shebang "#!/usr/bin/env node" will not work in debian-like systems (it should be nodejs instead of node).

**Comment by gevorg** [comment]
Thanks for letting me know, formatting was obviously wrong, I have this problem again and again :(

For shebang, I don't know proper solution that works on all platforms, but I know that is common practice for node developers to create symbolic link `node` and point it to `nodejs`.

**Comment by jesuslinares** [comment]
Now it is working. It would be great if you change the shebang according to the operative system. Thanks.

**Comment by gevorg** [comment]
Yeah, I just added tests also so hopefully it will never happen again, unfortunately I don't know any good way of changing shebang :(
